name: "TE API"
description: "TE API"
version: "1.0.0"
slug: "teapi"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
options:
    mqtt_ip: ""
    mqtt_username: ""
    mqtt_password: ""
    teapi_username: ""
    teapi_password: ""
schema:
    mqtt_ip: str
    mqtt_username: str
    mqtt_password: password
    teapi_username: str
    teapi_password: password
